/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as PlayCreateRouteImport } from './routes/play/create'
import { Route as ConfigStatsRouteImport } from './routes/config/stats'
import { Route as ConfigSkillsRouteImport } from './routes/config/skills'
import { Route as ConfigRacesRouteImport } from './routes/config/races'
import { Route as ConfigMaterialsRouteImport } from './routes/config/materials'
import { Route as ConfigItemsRouteImport } from './routes/config/items'
import { Route as ConfigCurrencyRouteImport } from './routes/config/currency'
import { Route as PlayCharacterIdRouteImport } from './routes/play/character.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCreateRoute = PlayCreateRouteImport.update({
  id: '/play/create',
  path: '/play/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigStatsRoute = ConfigStatsRouteImport.update({
  id: '/config/stats',
  path: '/config/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigSkillsRoute = ConfigSkillsRouteImport.update({
  id: '/config/skills',
  path: '/config/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRacesRoute = ConfigRacesRouteImport.update({
  id: '/config/races',
  path: '/config/races',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigMaterialsRoute = ConfigMaterialsRouteImport.update({
  id: '/config/materials',
  path: '/config/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigItemsRoute = ConfigItemsRouteImport.update({
  id: '/config/items',
  path: '/config/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigCurrencyRoute = ConfigCurrencyRouteImport.update({
  id: '/config/currency',
  path: '/config/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCharacterIdRoute = PlayCharacterIdRouteImport.update({
  id: '/play/character/$id',
  path: '/play/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config/currency': typeof ConfigCurrencyRoute
  '/config/items': typeof ConfigItemsRoute
  '/config/materials': typeof ConfigMaterialsRoute
  '/config/races': typeof ConfigRacesRoute
  '/config/skills': typeof ConfigSkillsRoute
  '/config/stats': typeof ConfigStatsRoute
  '/play/create': typeof PlayCreateRoute
  '/config/': typeof ConfigIndexRoute
  '/play/': typeof PlayIndexRoute
  '/play/character/$id': typeof PlayCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config/currency': typeof ConfigCurrencyRoute
  '/config/items': typeof ConfigItemsRoute
  '/config/materials': typeof ConfigMaterialsRoute
  '/config/races': typeof ConfigRacesRoute
  '/config/skills': typeof ConfigSkillsRoute
  '/config/stats': typeof ConfigStatsRoute
  '/play/create': typeof PlayCreateRoute
  '/config': typeof ConfigIndexRoute
  '/play': typeof PlayIndexRoute
  '/play/character/$id': typeof PlayCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config/currency': typeof ConfigCurrencyRoute
  '/config/items': typeof ConfigItemsRoute
  '/config/materials': typeof ConfigMaterialsRoute
  '/config/races': typeof ConfigRacesRoute
  '/config/skills': typeof ConfigSkillsRoute
  '/config/stats': typeof ConfigStatsRoute
  '/play/create': typeof PlayCreateRoute
  '/config/': typeof ConfigIndexRoute
  '/play/': typeof PlayIndexRoute
  '/play/character/$id': typeof PlayCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config/currency'
    | '/config/items'
    | '/config/materials'
    | '/config/races'
    | '/config/skills'
    | '/config/stats'
    | '/play/create'
    | '/config/'
    | '/play/'
    | '/play/character/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config/currency'
    | '/config/items'
    | '/config/materials'
    | '/config/races'
    | '/config/skills'
    | '/config/stats'
    | '/play/create'
    | '/config'
    | '/play'
    | '/play/character/$id'
  id:
    | '__root__'
    | '/'
    | '/config/currency'
    | '/config/items'
    | '/config/materials'
    | '/config/races'
    | '/config/skills'
    | '/config/stats'
    | '/play/create'
    | '/config/'
    | '/play/'
    | '/play/character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigCurrencyRoute: typeof ConfigCurrencyRoute
  ConfigItemsRoute: typeof ConfigItemsRoute
  ConfigMaterialsRoute: typeof ConfigMaterialsRoute
  ConfigRacesRoute: typeof ConfigRacesRoute
  ConfigSkillsRoute: typeof ConfigSkillsRoute
  ConfigStatsRoute: typeof ConfigStatsRoute
  PlayCreateRoute: typeof PlayCreateRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlayCharacterIdRoute: typeof PlayCharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/create': {
      id: '/play/create'
      path: '/play/create'
      fullPath: '/play/create'
      preLoaderRoute: typeof PlayCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/stats': {
      id: '/config/stats'
      path: '/config/stats'
      fullPath: '/config/stats'
      preLoaderRoute: typeof ConfigStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/skills': {
      id: '/config/skills'
      path: '/config/skills'
      fullPath: '/config/skills'
      preLoaderRoute: typeof ConfigSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/races': {
      id: '/config/races'
      path: '/config/races'
      fullPath: '/config/races'
      preLoaderRoute: typeof ConfigRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/materials': {
      id: '/config/materials'
      path: '/config/materials'
      fullPath: '/config/materials'
      preLoaderRoute: typeof ConfigMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/items': {
      id: '/config/items'
      path: '/config/items'
      fullPath: '/config/items'
      preLoaderRoute: typeof ConfigItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/currency': {
      id: '/config/currency'
      path: '/config/currency'
      fullPath: '/config/currency'
      preLoaderRoute: typeof ConfigCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/character/$id': {
      id: '/play/character/$id'
      path: '/play/character/$id'
      fullPath: '/play/character/$id'
      preLoaderRoute: typeof PlayCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigCurrencyRoute: ConfigCurrencyRoute,
  ConfigItemsRoute: ConfigItemsRoute,
  ConfigMaterialsRoute: ConfigMaterialsRoute,
  ConfigRacesRoute: ConfigRacesRoute,
  ConfigSkillsRoute: ConfigSkillsRoute,
  ConfigStatsRoute: ConfigStatsRoute,
  PlayCreateRoute: PlayCreateRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlayCharacterIdRoute: PlayCharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
